version: "3.7"

services:
  transmission:
    image : jaymoulin/transmission:4.0.4
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: ghcr.io/hotio/jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Mexico_City
    volumes:
      - ./jackett/data:/config
    restart: unless-stopped